import 'dart:convert';
import 'dart:io';

Future<void> main(List<String> args) async {
  final tag =
      Platform.environment['CM_TAG'] ?? Platform.environment['GITHUB_REF_NAME'];
  if (tag == null || tag.isEmpty) {
    stdout.writeln('Not a tag build; skipping GitHub Release publishing.');
    return;
  }

  final token = Platform.environment['GITHUB_TOKEN'];
  if (token == null || token.isEmpty) {
    stdout.writeln(
      'GITHUB_TOKEN is missing; skipping GitHub Release publishing.',
    );
    return;
  }

  final repo =
      Platform.environment['GITHUB_REPOSITORY'] ??
      Platform.environment['CM_REPO_SLUG'] ??
      await _repoSlugFromGit();
  if (repo == null || !repo.contains('/')) {
    stderr.writeln('Unable to resolve GitHub repository slug.');
    exitCode = 1;
    return;
  }

  final files = args.map(File.new).where((file) => file.existsSync()).toList();
  if (files.isEmpty) {
    stdout.writeln(
      'No release assets found; skipping GitHub Release publishing.',
    );
    return;
  }

  final client = _GitHubClient(token);
  final release =
      await client.releaseForTag(repo, tag) ??
      await client.createRelease(repo, tag);
  final releaseId = release['id'] as int;
  final uploadUrl = (release['upload_url'] as String).split('{').first;
  final existingAssets = await client.assets(repo, releaseId);

  for (final file in files) {
    final name = file.uri.pathSegments.last;
    for (final asset in existingAssets.where(
      (asset) => asset['name'] == name,
    )) {
      await client.deleteAsset(repo, asset['id'] as int);
    }
    await client.uploadAsset(uploadUrl, name, file);
    stdout.writeln('Uploaded $name to GitHub Release $tag.');
  }

  client.close();
}

Future<String?> _repoSlugFromGit() async {
  final result = await Process.run('git', [
    'config',
    '--get',
    'remote.origin.url',
  ]);
  if (result.exitCode != 0) return null;
  final remote = (result.stdout as String).trim();
  final httpsMatch = RegExp(
    r'github\.com[:/]([^/]+/[^/.]+)(?:\.git)?$',
  ).firstMatch(remote);
  return httpsMatch?.group(1);
}

class _GitHubClient {
  _GitHubClient(this.token);

  final String token;
  final HttpClient _client = HttpClient();

  Future<Map<String, Object?>?> releaseForTag(String repo, String tag) async {
    final response = await _request('GET', '/repos/$repo/releases/tags/$tag');
    if (response.statusCode == 404) return null;
    return _json(response);
  }

  Future<Map<String, Object?>> createRelease(String repo, String tag) async {
    final response = await _request(
      'POST',
      '/repos/$repo/releases',
      body: {
        'tag_name': tag,
        'name': 'StudyHUB $tag',
        'body': 'Automated StudyHUB release generated by Codemagic.',
        'draft': false,
        'prerelease': tag.contains('-'),
      },
    );
    if (response.statusCode == 422) {
      final existing = await releaseForTag(repo, tag);
      if (existing != null) return existing;
    }
    return _json(response);
  }

  Future<List<Map<String, Object?>>> assets(String repo, int releaseId) async {
    final response = await _request(
      'GET',
      '/repos/$repo/releases/$releaseId/assets',
    );
    final decoded =
        jsonDecode(await response.transform(utf8.decoder).join())
            as List<Object?>;
    return decoded.cast<Map<String, Object?>>();
  }

  Future<void> deleteAsset(String repo, int assetId) async {
    final response = await _request(
      'DELETE',
      '/repos/$repo/releases/assets/$assetId',
    );
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw HttpException(
        'Failed to delete GitHub release asset: ${response.statusCode}',
      );
    }
  }

  Future<void> uploadAsset(String uploadUrl, String name, File file) async {
    final uri = Uri.parse(uploadUrl).replace(queryParameters: {'name': name});
    final request = await _client.postUrl(uri);
    _headers(request, accept: false);
    request.headers.contentType = ContentType.binary;
    request.headers.contentLength = await file.length();
    await request.addStream(file.openRead());
    final response = await request.close();
    if (response.statusCode < 200 || response.statusCode >= 300) {
      final body = await response.transform(utf8.decoder).join();
      throw HttpException(
        'Failed to upload $name: ${response.statusCode} $body',
      );
    }
  }

  Future<HttpClientResponse> _request(
    String method,
    String path, {
    Map<String, Object?>? body,
  }) async {
    final request = await _client.openUrl(
      method,
      Uri.https('api.github.com', path),
    );
    _headers(request);
    if (body != null) {
      request.headers.contentType = ContentType.json;
      request.write(jsonEncode(body));
    }
    final response = await request.close();
    if (response.statusCode < 200 || response.statusCode >= 300) {
      if (response.statusCode == 404) return response;
      final responseBody = await response.transform(utf8.decoder).join();
      throw HttpException(
        'GitHub API failed: ${response.statusCode} $responseBody',
      );
    }
    return response;
  }

  void _headers(HttpClientRequest request, {bool accept = true}) {
    request.headers.set(HttpHeaders.authorizationHeader, 'Bearer $token');
    request.headers.set('X-GitHub-Api-Version', '2022-11-28');
    request.headers.set(HttpHeaders.userAgentHeader, 'StudyHUB-Codemagic');
    if (accept) {
      request.headers.set(
        HttpHeaders.acceptHeader,
        'application/vnd.github+json',
      );
    }
  }

  Future<Map<String, Object?>> _json(HttpClientResponse response) async {
    final decoded =
        jsonDecode(await response.transform(utf8.decoder).join())
            as Map<String, Object?>;
    return decoded;
  }

  void close() => _client.close(force: true);
}
